#' @title Additional useful packages
#' @description Installs additional packages useful for geology, statistics, and visualization.
#' @export
#' @return Installed packages
#'
additional_pks <- function (){
  install.packages("sf")
  install.packages("raster")
  install.packages("gstat")
  install.packages("geoR")
  install.packages("automap")
  install.packages("OneTwoSamples")
  install.packages("rgl")
  install.packages("car")
  install.packages("rgdal")
  install.packages("tmap")
  install.packages("janitor")
  install.packages("ggpubr")
  install.packages("sjPlot")
  install.packages("rockchalk")
  install.packages("effsize")
  install.packages("Metrics")
  install.packages("highcharter")
  install.packages("leaflet")
  install.packages("rpart.plot")
  install.packages("provenance")
  install.packages(c("ggspatial", "inlabru", "rbokeh", 'rayshader'))
  install.packages("DMwR")
  install.packages("psycho")
  install.packages("tidymodels")
  install.packages("tidyverse")
  install.packages(c("BEST", "tidybayes"))
  install.packages("latex2exp")
  install.packages("binom")
  install.packages(c("RVAideMemoire", "EMT", "XNomial"))
  install.packages(c("compositions", "zCompositions", "easyCODA",
                     "Ternary", "ggtern")) # CoDA
  install.packages(c("ggstatsplot", "ggalluvial", "easyalluvial",
                     "ggmosaic", "dendextend"))
  install.packages(c("xaringan", "citr", "bookdown", "prettydoc", "kableExtra"))
  install.packages("rpivotTable")
  install.packages("esquisse")
  install.packages("ggeffects")
  install.packages("MOTE")
  install.packages("vcdExtra")
  install.packages(c("georob", "geoCount", "spBayes"))
  install.packages("see")
  install.packages(c("ClustGeo", "factoextra", "NbClust"))
  install.packages(c("georob", "geoCount"))
  install.packages(c("leafpm", "mapedit"))
  install.packages("ggforce")
  install.packages("ggfortify")
  install.packages("ggtext")
  install.packages("marmap")
  install.packages("cptcity")
  install.packages("patchwork")
  install.packages("gghighlight")
  install.packages("rstatix")
  install.packages("summarytools")
  install.packages(c("gtsummary", "explor"))
  install.packages("rcompanion")
  install.packages("modelbased")
  install.packages("cocor")
  install.packages("lmtest")
  install.packages("conflicted")
  install.packages("vroom")
  install.packages("flextable")
  install.packages("ftExtra")
  install.packages("flexdashboard")
  install.packages("dygraphs")
  # install.packages("rstanarm")
  # install.packages("brms")
  install.packages("devtools")
  remotes::install_github("ramnathv/tidymetrics")
  remotes::install_github('crsh/papaja')
  remotes::install_github('gitrman/itns')
  remotes::install_github('easystats/easystats')
}
