#' @title Additional useful packages
#' @description Installs additional packages useful for geology, statistics, and visualization.
#' @export
#' @return Installed packages
#'
additional_pks <- function (){
  utils::install.packages("sf")
  utils::install.packages("raster")
  utils::install.packages("gstat")
  utils::install.packages("geoR")
  utils::install.packages("automap")
  utils::install.packages("OneTwoSamples")
  utils::install.packages("rgl")
  utils::install.packages("car")
  utils::install.packages("rgdal")
  utils::install.packages("tmap")
  utils::install.packages("janitor")
  utils::install.packages("ggpubr")
  utils::install.packages("sjPlot")
  utils::install.packages("rockchalk")
  # utils::install.packages("effsize")
  utils::install.packages("Metrics")
  utils::install.packages("highcharter")
  utils::install.packages("leaflet")
  utils::install.packages("rpart.plot")
  utils::install.packages("provenance")
  utils::install.packages(c("ggspatial", "inlabru", "rbokeh", 'rayshader'))
  # utils::install.packages("DMwR")
  utils::install.packages("psycho")
  utils::install.packages("tidymodels")
  utils::install.packages("tidyverse")
  utils::install.packages(c("BEST", "tidybayes"))
  utils::install.packages("latex2exp")
  utils::install.packages("binom")
  utils::install.packages(c("RVAideMemoire", "EMT", "XNomial"))
  utils::install.packages(c("zCompositions", "easyCODA",
                     "robCompositions", "Ternary")) # CoDA
  utils::install.packages(c("ggstatsplot", "ggalluvial", "easyalluvial",
                     "ggmosaic", "dendextend"))
  utils::install.packages(c("xaringan", "bookdown", "kableExtra", "quarto"))
  utils::install.packages("rpivotTable")
  utils::install.packages("esquisse")
  # utils::install.packages("ggeffects")
  utils::install.packages("MOTE")
  utils::install.packages("vcdExtra")
  # utils::install.packages(c("georob", "geoCount", "spBayes"))
  utils::install.packages("corrr")
  utils::install.packages(c("ClustGeo", "factoextra", "NbClust"))
  utils::install.packages(c("leafpm", "mapedit"))
  utils::install.packages("ggforce")
  utils::install.packages("ggfortify")
  utils::install.packages("ggtext")
  utils::install.packages("marmap")
  utils::install.packages("cptcity")
  utils::install.packages("patchwork")
  utils::install.packages("gghighlight")
  # utils::install.packages("rstatix")
  utils::install.packages("summarytools")
  utils::install.packages(c("gtsummary", "explor", "dlookr"))
  utils::install.packages("rcompanion")
  utils::install.packages("modelbased")
  utils::install.packages("cocor")
  utils::install.packages("lmtest")
  # utils::install.packages("conflicted")
  utils::install.packages("vroom")
  utils::install.packages("flextable")
  utils::install.packages("ftExtra")
  utils::install.packages("flexdashboard")
  utils::install.packages("dygraphs")
  # utils::install.packages("rstanarm")
  # utils::install.packages("brms")
  utils::install.packages("devtools")
  utils::install.packages("modelsummary")
  utils::install.packages("GGally")
  remotes:install_github("ramnathv/tidymetrics")
  remotes::install_github('crsh/papaja')
  remotes::install_github('gitrman/itns')
  remotes::install_github('easystats/easystats')
}
