#' @title Additional useful packages
#' @description Installs additional packages useful for geology, statistics, and visualization.
#' @export
#' @return Installed packages
#'
additional_pks <- function (){
  install.packages("sf", dep=T)
  install.packages("raster", dep=T)
  install.packages("gstat", dep=T)
  install.packages("geoR", dep=T)
  install.packages("automap", dep=T)
  install.packages("OneTwoSamples", dep=T)
  install.packages("rgl", dep=T)
  install.packages("car", dep=T)
  install.packages("rgdal", dep=T)
  install.packages("tmap", dep=T)
  install.packages("ggpubr", dep=T)
  install.packages("sjPlot", dep=T)
  install.packages("rockchalk", dep=T)
  install.packages("effsize", dep=T)
  install.packages("Metrics", dep=T)
  install.packages("plotmo", dep=T)
  install.packages("highcharter", dep=T)
  install.packages("leaflet", dep=T)
  install.packages("caret", dep=T)
  install.packages("rpart.plot", dep=T)
  install.packages("provenance", dep=T)
  install.packages("infer", dep=T)
  install.packages("visreg", dep=T)
  install.packages(c("ggspatial", "inlabru", "rbokeh", 'rayshader'), dep=T)
  install.packages("heavy", dep=T)
  install.packages("DMwR", dep=T)
  install.packages("psycho", dep=T)
  install.packages("tidyverse", dep=T)
  install.packages("latex2exp", dep=T)
  install.packages("binom", dep=T)
  # install.packages("heplots", dep=T)
  install.packages(c("RVAideMemoire", "EMT", "XNomial", "ggmosaic"))
  install.packages(c("xaringan", "citr", "bookdown"))
  install.packages("CircStats", dep=T)
  install.packages("vistributions", dep=T)
  install.packages("rpivotTable", dep=T)
  install.packages("esquisse", dep=T)
  devtools::install_github('doomlab/MOTE')
  devtools::install_github('gitrman/itns')
}
